x-botforge-base: &botforge-base
  image: "${BOTFORGE_IMAGE:-ghcr.io/botworkz/tools/botforge}"
  user: "${HOST_UID:?}:${HOST_GID:?}"
  group_add:
  - "${HOST_KVM_GID}"
  working_dir: ${REPO_ROOT:-${PWD}}
  environment:
    HOME: /tmp
    XDG_CACHE_HOME: /tmp/.cache
    HOST_UID: ${HOST_UID}
    HOST_GID: ${HOST_GID}
    HOST_KVM_GID: ${HOST_KVM_GID}
    LIBGUESTFS_BACKEND: direct
  volumes:
  - ${REPO_ROOT:-${PWD}}:${REPO_ROOT:-${PWD}}

services:
  botforge:
    <<: *botforge-base
    devices:
    - /dev/kvm:/dev/kvm

  image-build:
    <<: *botforge-base
    devices:
    - /dev/kvm:/dev/kvm

  test:
    <<: *botforge-base
    devices:
    - /dev/kvm:/dev/kvm

  deps:
    <<: *botforge-base
