type: build
image: >-
  @debian-base
disk_size: 10G
memsize: 4096
smp: 4

uploads:
- src: images/botwork-base/provisioners/00-base.sh
  dest: /tmp/00-base.sh
- src: images/botwork-base/provisioners/10-bot-user.sh
  dest: /tmp/10-bot-user.sh
- src: images/botwork-base/provisioners/99-cleanup.sh
  dest: /tmp/99-cleanup.sh

steps:
- on: guest
  name: base
  run: sudo bash /tmp/00-base.sh
- on: guest
  name: bot-user
  run: sudo bash /tmp/10-bot-user.sh
- on: guest
  name: cleanup
  run: sudo bash /tmp/99-cleanup.sh
