#!/usr/bin/env bash
# Provisioners are executed by `botforge build` via `sudo bash /tmp/<script>.sh`
# in a booted guest. Keep this script POSIX/dash-clean too; see 00-base.sh.
set -eux

# Drop any orphans pulled in transiently by the package installs in
# 00-base.sh / 20-botwork-stack.sh. --purge so we also drop config
# files for removed packages; -y because we're non-interactive.
apt-get autoremove --purge -y || true

apt-get clean || true
rm -rf /var/lib/apt/lists/*
rm -f /etc/dpkg/dpkg.cfg.d/02apt-speedup

# Stop future `apt-get update` runs (e.g. unattended-upgrades.service)
# from pulling translation packs we never use. Saves ~5-10MB per
# `apt-get update` over the VM's lifetime.
cat >/etc/apt/apt.conf.d/99-no-translations <<'EOF'
Acquire::Languages "none";
EOF
chmod 0644 /etc/apt/apt.conf.d/99-no-translations

# Routine package-management cruft. *-old files are debconf's own
# rotation; aux-cache is regenerated by ldconfig on first boot.
rm -f /var/cache/debconf/*-old
rm -f /var/cache/ldconfig/aux-cache

truncate -s 0 /etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id

# Clear journald BEFORE truncating /var/log: truncating binary journal
# files (.journal under /var/log/journal/) corrupts them — journald
# refuses to read a 0-byte file with a missing magic header and noisily
# rotates it on first boot. `journalctl --rotate && --vacuum-time=1s`
# is the supported clear path; we fall back to `rm -rf /var/log/journal/*`
# in case journalctl isn't reachable in this build environment (for example in
# non-systemd/minimal contexts where `journalctl --rotate` exits non-zero).
# The rm covers that case; the journalctl call is for live-boot rebuilds.
if command -v journalctl >/dev/null 2>&1; then
  journalctl --rotate 2>/dev/null || true
  journalctl --vacuum-time=1s 2>/dev/null || true
fi
rm -rf /var/log/journal/* 2>/dev/null || true

# Now safe to zero text logs.
find /var/log -type f ! -path '/var/log/journal/*' -exec truncate -s 0 {} \;
rm -rf /home/debian/.ssh /home/bot/.ssh /root/.ssh || true
# Remove pre-generated SSH host keys so every VM gets its own identity on
# first boot. The Debian `openssh-server` package's ssh.service runs
# `/usr/lib/openssh/sshd-session` (Debian 12+) which has an ExecStartPre
# that calls `dpkg-reconfigure openssh-server --frontend=noninteractive`
# when the host keys are missing — that generates a fresh ed25519 + RSA
# pair on first boot. We do NOT need a custom regen unit.
rm -f /etc/ssh/ssh_host_*

# Same reason as SSH host keys: every VM seeded from this image would
# otherwise start with the same entropy seed. systemd-random-seed.service
# regenerates this on first boot if missing.
rm -f /var/lib/systemd/random-seed

if command -v cloud-init >/dev/null 2>&1; then
  cloud-init clean --logs --seed || true
fi
rm -f /root/.bash_history /home/debian/.bash_history /home/bot/.bash_history || true

# Belt-and-braces: 20-botwork-stack.sh removes /tmp/botwork-build-context
# itself, but any other transient state under /tmp /var/tmp from the
# provisioner runs has no reason to ship in the image.
rm -rf /tmp/* /tmp/.* /var/tmp/* 2>/dev/null || true

# Stale DHCP / NetworkManager lease files would pin the build-time IP
# guess into every booted VM until the lease expires. Shouldn't be
# present in normal image builds, but belt-and-braces.
rm -rf /var/lib/dhcp/* /var/lib/NetworkManager/* 2>/dev/null || true

# Strip non-English locale data. ~30-50MB on a stock Debian rootfs;
# the VM only runs English-locale workloads (broker logs, systemd
# units, operator SSH). Keep `en*`, `C`, and `POSIX`. We do NOT pull
# in `localepurge` (which would require a package install + a debconf
# preseed); a plain `find` does the same job with no new dependency.
#
# `-mindepth 1 -maxdepth 1` so we only remove top-level locale dirs,
# not files in /usr/share/locale itself (e.g. locale.alias).
find /usr/share/locale -mindepth 1 -maxdepth 1 -type d \
  ! -name 'en*' ! -name 'C' ! -name 'POSIX' \
  -exec rm -rf {} +

# Zero-fill free space before fstrim so the eventual `qemu-img convert
# -O qcow2 -c` in scripts/pack.sh can compress the now-zero blocks down
# to ~nothing. fstrim alone returns blocks to the qcow2 backing layer
# but the compressed output still carries whatever bytes were there.
#
# Budget: ~1 GB/s on a modern SSD, so for a 16 GiB disk with ~13 GiB
# free this adds ~10-15 seconds to the build. Cheap.
#
# `|| true` because dd legitimately exits 1 when the filesystem fills
# (which is the entire point — we want it to fill).
if [ -w / ]; then
  dd if=/dev/zero of=/EMPTY bs=1M status=none 2>/dev/null || true
  sync
  rm -f /EMPTY
  sync
fi

# fstrim is only meaningful when the filesystem is actually mounted on a
# block device. In non-block-device contexts (for example host chroot/container)
# it may error harmlessly. Either way: best-effort.
if command -v fstrim >/dev/null 2>&1; then
  fstrim -av || true
fi

sync
